openapi: 3.0.0
components:
    schemas:
        v1.AWSReservationRequest:
            type: object
            properties:
                amount:
                    type: integer
                    format: int32
                image_id:
                    type: string
                instance_type:
                    type: string
                launch_template_id:
                    type: string
                name:
                    type: string
                poweroff:
                    type: boolean
                pubkey_id:
                    type: integer
                    format: int64
                region:
                    type: string
                source_id:
                    type: string
        v1.AWSReservationResponse:
            type: object
            properties:
                amount:
                    type: integer
                    format: int32
                aws_reservation_id:
                    type: string
                image_id:
                    type: string
                instance_type:
                    type: string
                instances:
                    type: array
                    items:
                        type: object
                        properties:
                            detail:
                                type: object
                                properties:
                                    private_ipv4:
                                        type: string
                                    private_ipv6:
                                        type: string
                                    public_dns:
                                        type: string
                                    public_ipv4:
                                        type: string
                            instance_id:
                                type: string
                launch_template_id:
                    type: string
                name:
                    type: string
                poweroff:
                    type: boolean
                pubkey_id:
                    type: integer
                    format: int64
                region:
                    type: string
                reservation_id:
                    type: integer
                    format: int64
                source_id:
                    type: string
        v1.AccountIDTypeResponse:
            type: object
            properties:
                aws:
                    type: object
                    properties:
                        account_id:
                            type: string
        v1.AvailabilityStatusRequest:
            type: object
            properties:
                source_id:
                    type: string
        v1.AzureReservationRequest:
            type: object
            properties:
                amount:
                    type: integer
                    format: int64
                image_id:
                    type: string
                instance_size:
                    type: string
                location:
                    type: string
                    description: Location (also known as region) to deploy the VM into, be aware it needs to be the same as the image location. Defaults to the Resource Group location, or 'eastus' when also creating the resource group.
                name:
                    type: string
                    description: Name of the instance, to keep names unique, it will be suffixed with UUID. Optional, defaults to 'redhat-vm''
                poweroff:
                    type: boolean
                pubkey_id:
                    type: integer
                    format: int64
                resource_group:
                    type: string
                    description: Azure resource group name to deploy the VM resources into. Optional, defaults to images resource group and when not found to 'redhat-deployed'.
                source_id:
                    type: string
        v1.AzureReservationResponse:
            type: object
            properties:
                amount:
                    type: integer
                    format: int64
                image_id:
                    type: string
                instance_size:
                    type: string
                instances:
                    type: array
                    items:
                        type: object
                        properties:
                            detail:
                                type: object
                                properties:
                                    private_ipv4:
                                        type: string
                                    private_ipv6:
                                        type: string
                                    public_dns:
                                        type: string
                                    public_ipv4:
                                        type: string
                            instance_id:
                                type: string
                location:
                    type: string
                name:
                    type: string
                poweroff:
                    type: boolean
                pubkey_id:
                    type: integer
                    format: int64
                reservation_id:
                    type: integer
                    format: int64
                resource_group:
                    type: string
                source_id:
                    type: string
        v1.GCPReservationRequest:
            type: object
            properties:
                amount:
                    type: integer
                    format: int64
                image_id:
                    type: string
                launch_template_id:
                    type: string
                machine_type:
                    type: string
                name_pattern:
                    type: string
                poweroff:
                    type: boolean
                pubkey_id:
                    type: integer
                    format: int64
                source_id:
                    type: string
                zone:
                    type: string
        v1.GCPReservationResponse:
            type: object
            properties:
                amount:
                    type: integer
                    format: int64
                gcp_operation_name:
                    type: string
                image_id:
                    type: string
                instances:
                    type: array
                    items:
                        type: object
                        properties:
                            detail:
                                type: object
                                properties:
                                    private_ipv4:
                                        type: string
                                    private_ipv6:
                                        type: string
                                    public_dns:
                                        type: string
                                    public_ipv4:
                                        type: string
                            instance_id:
                                type: string
                launch_template_id:
                    type: string
                machine_type:
                    type: string
                name_pattern:
                    type: string
                poweroff:
                    type: boolean
                pubkey_id:
                    type: integer
                    format: int64
                reservation_id:
                    type: integer
                    format: int64
                source_id:
                    type: string
                zone:
                    type: string
        v1.GenericReservationResponse:
            type: object
            properties:
                created_at:
                    type: string
                    format: date-time
                error:
                    type: string
                finished_at:
                    type: string
                    format: date-time
                    nullable: true
                id:
                    type: integer
                    format: int64
                provider:
                    type: integer
                status:
                    type: string
                step:
                    type: integer
                    format: int32
                step_titles:
                    type: array
                    items:
                        type: string
                steps:
                    type: integer
                    format: int32
                success:
                    type: boolean
                    nullable: true
        v1.InstanceTypeResponse:
            type: object
            properties:
                architecture:
                    type: string
                azure:
                    type: object
                    properties:
                        gen_v1:
                            type: boolean
                        gen_v2:
                            type: boolean
                cores:
                    type: integer
                    format: int32
                memory_mib:
                    type: integer
                    format: int64
                name:
                    type: string
                storage_gb:
                    type: integer
                    format: int64
                supported:
                    type: boolean
                vcpus:
                    type: integer
                    format: int32
        v1.LaunchTemplatesResponse:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
        v1.ListGenericReservationResponse:
            type: object
            properties:
                data:
                    type: array
                    items:
                        type: object
                        properties:
                            created_at:
                                type: string
                                format: date-time
                            error:
                                type: string
                            finished_at:
                                type: string
                                format: date-time
                                nullable: true
                            id:
                                type: integer
                                format: int64
                            provider:
                                type: integer
                            status:
                                type: string
                            step:
                                type: integer
                                format: int32
                            step_titles:
                                type: array
                                items:
                                    type: string
                            steps:
                                type: integer
                                format: int32
                            success:
                                type: boolean
                                nullable: true
                metadata:
                    type: object
                    properties:
                        links:
                            type: object
                            properties:
                                next:
                                    type: string
                                previous:
                                    type: string
                        total:
                            type: integer
        v1.ListInstaceTypeResponse:
            type: object
            properties:
                data:
                    type: array
                    items:
                        type: object
                        properties:
                            architecture:
                                type: string
                            azure:
                                type: object
                                properties:
                                    gen_v1:
                                        type: boolean
                                    gen_v2:
                                        type: boolean
                            cores:
                                type: integer
                                format: int32
                            memory_mib:
                                type: integer
                                format: int64
                            name:
                                type: string
                            storage_gb:
                                type: integer
                                format: int64
                            supported:
                                type: boolean
                            vcpus:
                                type: integer
                                format: int32
        v1.ListLaunchTemplateResponse:
            type: object
            properties:
                data:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: string
                            name:
                                type: string
                metadata:
                    type: object
                    properties:
                        links:
                            type: object
                            properties:
                                next:
                                    type: string
                                previous:
                                    type: string
                        total:
                            type: integer
        v1.ListPubkeyResponse:
            type: object
            properties:
                data:
                    type: array
                    items:
                        type: object
                        properties:
                            body:
                                type: string
                            fingerprint:
                                type: string
                            fingerprint_legacy:
                                type: string
                            id:
                                type: integer
                                format: int64
                            name:
                                type: string
                            type:
                                type: string
                metadata:
                    type: object
                    properties:
                        links:
                            type: object
                            properties:
                                next:
                                    type: string
                                previous:
                                    type: string
                        total:
                            type: integer
        v1.ListSourceResponse:
            type: object
            properties:
                data:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: string
                            name:
                                type: string
                            provider:
                                type: string
                                description: One of ('azure', 'aws', 'gcp')
                            source_type_id:
                                type: string
                                deprecated: true
                            status:
                                type: string
                            uid:
                                type: string
                metadata:
                    type: object
                    properties:
                        links:
                            type: object
                            properties:
                                next:
                                    type: string
                                previous:
                                    type: string
                        total:
                            type: integer
        v1.NoopReservationResponse:
            type: object
            properties:
                reservation_id:
                    type: integer
                    format: int64
        v1.PubkeyRequest:
            type: object
            properties:
                body:
                    type: string
                    description: Add a public part of a SSH key pair.
                name:
                    type: string
                    description: Enter the name of the newly created pubkey.
        v1.PubkeyResponse:
            type: object
            properties:
                body:
                    type: string
                fingerprint:
                    type: string
                fingerprint_legacy:
                    type: string
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                type:
                    type: string
        v1.ResponseError:
            type: object
            properties:
                build_time:
                    type: string
                edge_id:
                    type: string
                environment:
                    type: string
                error:
                    type: string
                msg:
                    type: string
                trace_id:
                    type: string
                version:
                    type: string
        v1.SourceResponse:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                provider:
                    type: string
                    description: One of ('azure', 'aws', 'gcp')
                source_type_id:
                    type: string
                    deprecated: true
                status:
                    type: string
                uid:
                    type: string
        v1.SourceUploadInfoResponse:
            type: object
            properties:
                aws:
                    type: object
                    nullable: true
                    properties:
                        account_id:
                            type: string
                azure:
                    type: object
                    nullable: true
                    properties:
                        resource_groups:
                            type: array
                            items:
                                type: string
                        subscription_id:
                            type: string
                        tenant_id:
                            type: string
                gcp:
                    nullable: true
                provider:
                    type: string
    parameters:
        Limit:
            name: limit
            in: query
            description: The number of items to return.
            schema:
                type: integer
                default: 100
        Offset:
            name: offset
            in: query
            description: The number of items to skip before starting to collect the result set.
            schema:
                type: integer
                default: 0
        Token:
            name: token
            in: query
            description: The token used for requesting the next page of results; empty token for the first page
            schema:
                type: string
                default: ""
    responses:
        BadRequest:
            description: The request's parameters are not valid
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/v1.ResponseError'
                    examples:
                        error:
                            value:
                                build_time: 2023-04-14_17:15:02
                                edge_id: ""
                                environment: ""
                                error: 'error: bad request: details can be long'
                                trace_id: b57f7b78c
                                version: df8a489
        InternalError:
            description: The server encountered an internal error
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/v1.ResponseError'
                    examples:
                        error:
                            value:
                                build_time: 2023-04-14_17:15:02
                                edge_id: ""
                                environment: ""
                                error: 'error: this can be pretty long string'
                                trace_id: b57f7b78c
                                version: df8a489
        NotFound:
            description: The requested resource was not found
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/v1.ResponseError'
                    examples:
                        error:
                            value:
                                build_time: 2023-04-14_17:15:02
                                edge_id: ""
                                environment: ""
                                error: 'error: resource not found: details can be long'
                                trace_id: b57f7b78c
                                version: df8a489
    examples:
        v1.AvailabilityStatusRequest:
            value:
                source_id: "463243"
        v1.AwsReservationRequestPayloadExample:
            value:
                amount: 1
                image_id: ami-7846387643232
                instance_type: t3.small
                launch_template_id: ""
                name: my-instance
                poweroff: false
                pubkey_id: 42
                region: us-east-1
                source_id: "654321"
        v1.AwsReservationResponsePayloadDoneExample:
            value:
                amount: 1
                aws_reservation_id: r-3743243324231
                image_id: ami-7846387643232
                instance_type: t3.small
                instances:
                    - detail:
                        privateipv4: 172.31.36.10
                        privateipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7334
                        publicdns: ec2-184-73-141-211.compute-1.amazonaws.com
                        publicipv4: 184.73.141.211
                      instance_id: i-2324343212
                launch_template_id: ""
                name: my-instance
                poweroff: false
                pubkey_id: 42
                region: us-east-1
                reservation_id: 1305
                source_id: "654321"
        v1.AwsReservationResponsePayloadPendingExample:
            value:
                amount: 1
                aws_reservation_id: ""
                image_id: ami-7846387643232
                instance_type: t3.small
                instances: []
                launch_template_id: ""
                name: my-instance
                poweroff: false
                pubkey_id: 42
                region: us-east-1
                reservation_id: 0
                source_id: "654321"
        v1.AzureReservationRequestPayloadExample:
            value:
                amount: 1
                image_id: composer-api-081fc867-838f-44a5-af03-8b8def808431
                instance_size: Basic_A0
                location: useast
                name: my-instance
                poweroff: false
                pubkey_id: 42
                resource_group: redhat-hcc
                source_id: "654321"
        v1.AzureReservationResponsePayloadDoneExample:
            value:
                amount: 1
                image_id: composer-api-081fc867-838f-44a5-af03-8b8def808431
                instance_size: Basic_A0
                instances:
                    - detail:
                        privateipv4: 172.22.0.1
                        privateipv6: ""
                        publicdns: ""
                        publicipv4: 10.0.0.88
                      instance_id: /subscriptions/4b9d213f-712f-4d17-a483-8a10bbe9df3a/resourceGroups/redhat-deployed/providers/Microsoft.Compute/images/composer-api-92ea98f8-7697-472e-80b1-7454fa0e7fa7
                location: useast
                name: my-instance
                poweroff: false
                pubkey_id: 42
                reservation_id: 1310
                resource_group: myCustom Azure RG
                source_id: "654321"
        v1.AzureReservationResponsePayloadPendingExample:
            value:
                amount: 1
                image_id: composer-api-081fc867-838f-44a5-af03-8b8def808431
                instance_size: Basic_A0
                instances: []
                location: useast
                name: my-instance
                poweroff: false
                pubkey_id: 42
                reservation_id: 1310
                resource_group: myCustom Azure RG
                source_id: "654321"
        v1.GCPReservationRequestPayloadExample:
            value:
                amount: 1
                image_id: 08a48fed-de87-40ab-a571-f64e30bd0aa8
                launch_template_id: ""
                machine_type: e2-micro
                name_pattern: my-instance
                poweroff: false
                pubkey_id: 42
                source_id: "654321"
                zone: us-east-4
        v1.GCPReservationResponsePayloadDoneExample:
            value:
                amount: 1
                gcp_operation_name: operation-1686646674436-5fdff07e43209-66146b7e-f3f65ec5
                image_id: 08a48fed-de87-40ab-a571-f64e30bd0aa8
                instances:
                    - detail:
                        privateipv4: 10.198.0.2
                        privateipv6: ""
                        publicdns: ""
                        publicipv4: 10.0.0.88
                      instance_id: "3003942005876582747"
                launch_template_id: "4883371230199373111"
                machine_type: e2-micro
                name_pattern: my-instance
                poweroff: false
                pubkey_id: 42
                reservation_id: 1305
                source_id: "654321"
                zone: us-east-4
        v1.GCPReservationResponsePayloadPendingExample:
            value:
                amount: 1
                gcp_operation_name: operation-1686646674436-5fdff07e43209-66146b7e-f3f65ec5
                image_id: 08a48fed-de87-40ab-a571-f64e30bd0aa8
                instances: []
                launch_template_id: "4883371230199373111"
                machine_type: e2-micro
                name_pattern: my-instance
                poweroff: false
                pubkey_id: 42
                reservation_id: 1305
                source_id: "654321"
                zone: us-east-4
        v1.GenericReservationResponsePayloadFailureExample:
            value:
                created_at: "2013-05-13T19:20:15Z"
                error: 'cannot launch ec2 instance: VPCIdNotSpecified: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC'
                finished_at: "2013-05-13T19:20:25Z"
                id: 1313
                provider: 1
                status: Finished Launch instance(s)
                step: 2
                step_titles:
                    - Ensure public key
                    - Launch instance(s)
                    - Fetch instance(s) description
                steps: 3
                success: false
        v1.GenericReservationResponsePayloadListExample:
            value:
                data:
                    - created_at: "2013-05-13T19:20:15Z"
                      error: ""
                      finished_at: null
                      id: 1310
                      provider: 1
                      status: Started Ensure public key
                      step: 1
                      step_titles:
                        - Ensure public key
                        - Launch instance(s)
                        - Fetch instance(s) description
                      steps: 3
                      success: null
                    - created_at: "2013-05-13T19:20:15Z"
                      error: ""
                      finished_at: "2013-05-13T19:20:25Z"
                      id: 1305
                      provider: 1
                      status: Finished Fetch instance(s) description
                      step: 3
                      step_titles:
                        - Ensure public key
                        - Launch instance(s)
                        - Fetch instance(s) description
                      steps: 3
                      success: true
                    - created_at: "2013-05-13T19:20:15Z"
                      error: 'cannot launch ec2 instance: VPCIdNotSpecified: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC'
                      finished_at: "2013-05-13T19:20:25Z"
                      id: 1313
                      provider: 1
                      status: Finished Launch instance(s)
                      step: 2
                      step_titles:
                        - Ensure public key
                        - Launch instance(s)
                        - Fetch instance(s) description
                      steps: 3
                      success: false
                metadata:
                    links:
                        next: ""
                        previous: ""
                    total: 3
        v1.GenericReservationResponsePayloadPendingExample:
            value:
                created_at: "2013-05-13T19:20:15Z"
                error: ""
                finished_at: null
                id: 1310
                provider: 1
                status: Started Ensure public key
                step: 1
                step_titles:
                    - Ensure public key
                    - Launch instance(s)
                    - Fetch instance(s) description
                steps: 3
                success: null
        v1.GenericReservationResponsePayloadSuccessExample:
            value:
                created_at: "2013-05-13T19:20:15Z"
                error: ""
                finished_at: "2013-05-13T19:20:25Z"
                id: 1305
                provider: 1
                status: Finished Fetch instance(s) description
                step: 3
                step_titles:
                    - Ensure public key
                    - Launch instance(s)
                    - Fetch instance(s) description
                steps: 3
                success: true
        v1.InstanceTypesAWSResponse:
            value:
                data:
                    - arch: x86_64
                      cores: 16
                      memory_mib: 65536
                      name: c5a.8xlarge
                      storage_gb: 0
                      supported: true
                      vcpus: 32
        v1.InstanceTypesAzureResponse:
            value:
                data:
                    - arch: x86_64
                      azure:
                        gen_v1: true
                        gen_v2: true
                      cores: 64
                      memory_mib: 2e+06
                      name: Standard_M128s
                      storage_gb: 4096
                      supported: true
                      vcpus: 128
        v1.InstanceTypesGCPResponse:
            value:
                data:
                    - arch: x86_64
                      cores: 0
                      memory_mib: 15623
                      name: e2-highcpu-16
                      storage_gb: 0
                      supported: true
                      vcpus: 16
        v1.LaunchTemplateListResponse:
            value:
                data:
                    - id: lt-9843797432897342
                      name: XXL large backend API
                metadata:
                    links:
                        next: ""
                        previous: ""
                    total: 0
        v1.NoopReservationResponsePayloadExample:
            value:
                reservation_id: 1310
        v1.PubkeyListResponseExample:
            value:
                data:
                    - body: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEhnn80ZywmjeBFFOGm+cm+5HUwm62qTVnjKlOdYFLHN lzap
                      fingerprint: gL/y6MvNmJ8jDXtsL/oMmK8jUuIefN39BBuvYw/Rndk=
                      fingerprint_legacy: ee:f1:d4:62:99:ab:17:d9:3b:00:66:62:32:b2:55:9e
                      id: 3
                      name: My key
                      type: ssh-ed25519
                metadata:
                    links:
                        next: ""
                        previous: /api/provisioning/v1/pubkeys?limit=2&offset=0
                    total: 3
        v1.PubkeyRequestExample:
            value:
                body: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEhnn80ZywmjeBFFOGm+cm+5HUwm62qTVnjKlOdYFLHN lzap
                name: My key
        v1.PubkeyResponseExample:
            value:
                body: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEhnn80ZywmjeBFFOGm+cm+5HUwm62qTVnjKlOdYFLHN lzap
                fingerprint: gL/y6MvNmJ8jDXtsL/oMmK8jUuIefN39BBuvYw/Rndk=
                fingerprint_legacy: ee:f1:d4:62:99:ab:17:d9:3b:00:66:62:32:b2:55:9e
                id: 1
                name: My key
                type: ssh-ed25519
        v1.SourceListResponseExample:
            value:
                data:
                    - id: "654321"
                      name: My AWS account
                      provider: aws
                      source_type_id: ""
                      status: available
                      uid: ""
                    - id: "543621"
                      name: My other AWS account
                      provider: aws
                      source_type_id: ""
                      status: available
                      uid: ""
                metadata:
                    links:
                        next: ""
                        previous: /api/provisioning/v1/sources?limit=2&offset=0
                    total: 4
        v1.SourceUploadInfoAWSResponse:
            value:
                aws:
                    account_id: "78462784632"
                azure: null
                gcp: null
                provider: aws
        v1.SourceUploadInfoAzureResponse:
            value:
                aws: null
                azure:
                    resourcegroups:
                        - MyGroup 1
                        - MyGroup 42
                    subscriptionid: 617807e1-e4e0-4855-983c-1e3ce1e49674
                    tenantid: 617807e1-e4e0-481c-983c-be3ce1e49253
                gcp: null
                provider: azure
info:
    title: provisioning-api
    description: Provisioning service API
    license:
        name: GPL-3.0
    version: 1.13.0
paths: {}
servers:
    - url: http://0.0.0.0:{port}/api/{applicationName}
      description: Local development
      variables:
        applicationName:
            default: provisioning
        port:
            default: "8000"
tags:
    - name: Pubkey
      description: |
        A pubkey represents the SSH public portion of a key pair with a name and body. Public key types and fingerprints are detected during their creation process. Two types are supported: rsa and ed25519. Fingerprints are calculated in two ways: using the standard SHA method and the legacy MD5 method, which is available under the fingerprint_legacy field. Each public key has a unique name and body and helps in verifying the uniqueness of the keys. Using this API, you can perform the following operations.
    - name: Reservation
      description: |
        A reservation represents a request for launching one or more instances from a single image. This reservation triggers a background job, that will Launch set amount of instances with the same configuration. The configuration decides target provider, instance size and ssh pubkey to use for the default user.
    - name: Source
      description: |
        A Source represents a connection with public cloud account. These endpoints serve as convenient way to read information about available Sources to deploy instances into. The source of through is different application called Sources.
